[project]
name = "flow_reproassesslsm_st1"
version = "0.1.0"
description = "Flow_ReproAssessLSM_st1 using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=1.15.4,<2.0.0"
]

[project.scripts]
kickoff = "flow_reproassesslsm_st1.main:kickoff"
run_crew = "flow_reproassesslsm_st1.main:kickoff"
plot = "flow_reproassesslsm_st1.main:plot"
run_with_trigger = "flow_reproassesslsm_st1.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "flow"
